server:
    error:
        include-stacktrace: always
    port: 8443
    ssl:
        key-store: classpath:ssl.p12
        key-store-password: Test1234
        keyStoreType: PKCS12
    shutdown: graceful

nemlogin:
    signing:
        broker:
            signing-api-url: https://underskrift.test-nemlog-in.dk
            entity-id: https://broker-entity-id

            keystore-class-path: /TU-Test.p12
            key-pair-alias: "nemlog-in qualifiedsigning.testsp - interntest"
            keystore-password: Test1234
            private-key-password: Test1234

            saml:
                sp-entity-id: ${nemlogin.signing.broker.signing-api-url}/signing/auth/saml
                assertion-consumer-url: ${nemlogin.signing.broker.signing-api-url}/signing/auth/saml/assertion-consumer

                # SAML Assertion attributes
                attr-ssn-persistence-level: Global
                attr-cert-policy: Person
                attr-loa: Substantial
                attr-first-name: Jane
                attr-last-name: Fonda
                attr-email: jane.fonda@threemileisland.com
                attr-age: 103
                attr-anonymized: false
